// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarEXTI8DNlcyINHPA5q9XpQDAHgddcvc',
    appId: '1:1039925115925:web:dfa6f22cc9fa454b8aa21c',
    messagingSenderId: '1039925115925',
    projectId: 'cd-spotify-clone-18dfb',
    authDomain: 'cd-spotify-clone-18dfb.firebaseapp.com',
    storageBucket: 'cd-spotify-clone-18dfb.firebasestorage.app',
    measurementId: 'G-Y46PJRZPVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIl7P_otSRMmT4fQ9XZyUsP21bZQmRPKU',
    appId: '1:1039925115925:android:997e3052297aa8258aa21c',
    messagingSenderId: '1039925115925',
    projectId: 'cd-spotify-clone-18dfb',
    storageBucket: 'cd-spotify-clone-18dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPBFypG62YhU_4usvY53cj0M4fEuOwTMw',
    appId: '1:1039925115925:ios:b186201b0a1517cc8aa21c',
    messagingSenderId: '1039925115925',
    projectId: 'cd-spotify-clone-18dfb',
    storageBucket: 'cd-spotify-clone-18dfb.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPBFypG62YhU_4usvY53cj0M4fEuOwTMw',
    appId: '1:1039925115925:ios:b186201b0a1517cc8aa21c',
    messagingSenderId: '1039925115925',
    projectId: 'cd-spotify-clone-18dfb',
    storageBucket: 'cd-spotify-clone-18dfb.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDarEXTI8DNlcyINHPA5q9XpQDAHgddcvc',
    appId: '1:1039925115925:web:879480adb9a274888aa21c',
    messagingSenderId: '1039925115925',
    projectId: 'cd-spotify-clone-18dfb',
    authDomain: 'cd-spotify-clone-18dfb.firebaseapp.com',
    storageBucket: 'cd-spotify-clone-18dfb.firebasestorage.app',
    measurementId: 'G-TQGLYSGTQK',
  );
}
